'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8745
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("P0KeR.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property cardClubs10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardClubs10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardClubs2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardClubs2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardClubs3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardClubs3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardClubs4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardClubs4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardClubs5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardClubs5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardClubs6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardClubs6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardClubs7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardClubs7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardClubs8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardClubs8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardClubs9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardClubs9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardClubsA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardClubsA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardClubsJ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardClubsJ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardClubsK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardClubsK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardClubsQ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardClubsQ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardDiamonds10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardDiamonds10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardDiamonds2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardDiamonds2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardDiamonds3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardDiamonds3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardDiamonds4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardDiamonds4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardDiamonds5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardDiamonds5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardDiamonds6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardDiamonds6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardDiamonds7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardDiamonds7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardDiamonds8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardDiamonds8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardDiamonds9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardDiamonds9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardDiamondsA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardDiamondsA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardDiamondsJ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardDiamondsJ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardDiamondsK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardDiamondsK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardDiamondsQ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardDiamondsQ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardHearts10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardHearts10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardHearts2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardHearts2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardHearts3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardHearts3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardHearts4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardHearts4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardHearts5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardHearts5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardHearts6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardHearts6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardHearts7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardHearts7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardHearts8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardHearts8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardHearts9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardHearts9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardHeartsA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardHeartsA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardHeartsJ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardHeartsJ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardHeartsK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardHeartsK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardHeartsQ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardHeartsQ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardSpades10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardSpades10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardSpades2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardSpades2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardSpades3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardSpades3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardSpades4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardSpades4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardSpades5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardSpades5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardSpades6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardSpades6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardSpades7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardSpades7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardSpades8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardSpades8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardSpades9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardSpades9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardSpadesA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardSpadesA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardSpadesJ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardSpadesJ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardSpadesK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardSpadesK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardSpadesQ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardSpadesQ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property carlos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("carlos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flavio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flavio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property guilherme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("guilherme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jogadores() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jogadores", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property matheus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("matheus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property video_poker_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("video_poker_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
